.macro MAC_L_BC21
; ----------------------------------------------------------------------------
LBC1F:  .byte   $B0,$40                         ; BC1F
L_BC21: .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC21
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC29
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC31
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC39
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC41
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC49
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC51
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC59
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC61
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC69
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC71
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC79
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC81
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC89
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC91
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BC99
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BCA1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BCA9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BCB1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BCB9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BCC1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BCC9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BCD1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BCD9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BCE1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BCE9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BCF1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BCF9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD01
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD09
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD11
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD19
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD21
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD29
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD31
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD39
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD41
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD49
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD51
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD59
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD61
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD69
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD71
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD79
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD81
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD89
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD91
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BD99
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BDA1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BDA9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BDB1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BDB9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BDC1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BDC9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BDD1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BDD9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BDE1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BDE9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BDF1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BDF9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE01
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE09
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE11
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE19
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE21
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE29
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE31
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE39
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE41
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE49
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE51
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE59
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE61
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE69
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE71
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE79
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE81
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE89
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE91
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BE99
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BEA1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BEA9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BEB1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BEB9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BEC1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BEC9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BED1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BED9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BEE1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BEE9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BEF1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BEF9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF01
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF09
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF11
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF19
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF21
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF29
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF31
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF39
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF41
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF49
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF51
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF59
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF61
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF69
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF71
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF79
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF81
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF89
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF91
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BF99
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BFA1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BFA9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BFB1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BFB9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BFC1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BFC9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BFD1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BFD9
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BFE1
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF ; BFE9
        .byte   $FF,$FF,$FF,$EE,$F4,$FF,$4C,$3B ; BFF1
        .byte   $F2,$7E,$EB,$F4,$FF,$FF         ; BFF9
        .byte   $FF                             ; BFFF

; End of "BANK06" segment
; ----------------------------------------------------------------------------
.code

.endmacro

