.macro MAC_L_8000
L_8000: .addr   L8002                           ; 8000
L8002:  .addr   L_8124                          ; 8002
        .addr   L_8124                          ; 8004
        .addr   L92DB                           ; 8006
        .addr   L_8C64                          ; 8008
        .addr   L9009                           ; 800A
        .addr   L916E                           ; 800C
        .addr   L_8E97                          ; 800E
        .addr   L8CB0                           ; 8010
        .addr   L8AF8                           ; 8012
        .addr   L8B36                           ; 8014
        .addr   L8B74                           ; 8016
        .addr   L8BB2                           ; 8018
        .addr   L89E5                           ; 801A
        .addr   L8A0F                           ; 801C
        .addr   L8A1D                           ; 801E
        .addr   L8A2E                           ; 8020
        .addr   L8A58                           ; 8022
        .addr   L8A66                           ; 8024
        .addr   L_976D                          ; 8026
        .addr   L_9788                          ; 8028
        .addr   L_9882                          ; 802A
        .addr   L98A8                           ; 802C
        .addr   L_99CC                          ; 802E
        .addr   L99F0                           ; 8030
        .addr   L_9AEB                          ; 8032
        .addr   L_9B2F                          ; 8034
        .addr   L_815C                          ; 8036
        .addr   L855F                           ; 8038
        .addr   L8677                           ; 803A
        .addr   L8713                           ; 803C
        .addr   L873D                           ; 803E
        .addr   L874D                           ; 8040
        .addr   L875E                           ; 8042
        .addr   L8788                           ; 8044
        .addr   L8798                           ; 8046
        .addr   L_9D3B                          ; 8048
        .addr   L9D4C                           ; 804A
        .addr   L_9D3B                          ; 804C
        .addr   L9D5F                           ; 804E
        .addr   L_9D3B                          ; 8050
        .addr   L9D72                           ; 8052
        .addr   L882A                           ; 8054
        .addr   L8850                           ; 8056
        .addr   L_9C1C                          ; 8058
        .addr   L9C23                           ; 805A
        .addr   L9C38                           ; 805C
        .addr   L9C3F                           ; 805E
        .addr   L9C2A                           ; 8060
        .addr   L9C31                           ; 8062
        .addr   L9C46                           ; 8064
        .addr   L9C4D                           ; 8066
        .addr   L9C54                           ; 8068
        .addr   L9C68                           ; 806A
        .addr   L_9EA4                          ; 806C
; ----------------------------------------------------------------------------
        .byte   $00,$00                         ; 806E
; ----------------------------------------------------------------------------
        .addr   L9EBF                           ; 8070
        .addr   L9EE0                           ; 8072
        .addr   L9F39                           ; 8074
        .addr   L9F5A                           ; 8076
        .addr   L9FDA                           ; 8078
        .addr   L9FF9                           ; 807A
        .addr   LA02F                           ; 807C
        .addr   LA047                           ; 807E
        .addr   LA089                           ; 8080
        .addr   LA0B6                           ; 8082
        .addr   LA0F6                           ; 8084
        .addr   LA122                           ; 8086
        .addr   LA191                           ; 8088
        .addr   LA1AD                           ; 808A
        .addr   LA1F1                           ; 808C
        .addr   LA202                           ; 808E
        .addr   L_A237                          ; 8090
        .addr   LA24D                           ; 8092
        .addr   L_9B95                          ; 8094
        .addr   L9BAA                           ; 8096
        .addr   L_9BD8                          ; 8098
        .addr   L9BED                           ; 809A
        .addr   L_B1FF                          ; 809C
        .addr   LB20C                           ; 809E
        .addr   L_B29B                          ; 80A0
        .addr   LB2A8                           ; 80A2
        .addr   L_B62F                          ; 80A4
        .addr   LB63C                           ; 80A6
        .addr   L_A3E2                          ; 80A8
        .addr   LA40B                           ; 80AA
        .addr   L_A4DE                          ; 80AC
; ----------------------------------------------------------------------------
        .byte   $00,$00                         ; 80AE
; ----------------------------------------------------------------------------
        .addr   LA50E                           ; 80B0
        .addr   LA53A                           ; 80B2
        .addr   LA5C2                           ; 80B4
        .addr   L_A6D7                          ; 80B6
        .addr   LA6E4                           ; 80B8
        .addr   L_A74B                          ; 80BA
        .addr   LA76A                           ; 80BC
        .addr   L_A7CB                          ; 80BE
        .addr   LA7EE                           ; 80C0
        .addr   L_A86E                          ; 80C2
        .addr   L_A8D2                          ; 80C4
        .addr   LA8FB                           ; 80C6
        .addr   L_A9CB                          ; 80C8
        .addr   LA9DE                           ; 80CA
        .addr   L_AA5A                          ; 80CC
        .addr   LAA6C                           ; 80CE
        .addr   L_AB13                          ; 80D0
        .addr   LAB24                           ; 80D2
        .addr   L_ABCF                          ; 80D4
        .addr   LABEC                           ; 80D6
        .addr   L_AC3C                          ; 80D8
        .addr   LAC63                           ; 80DA
        .addr   L_ACFB                          ; 80DC
        .addr   LAD08                           ; 80DE
        .addr   L_ADE4                          ; 80E0
        .addr   LADFF                           ; 80E2
        .addr   L_AE78                          ; 80E4
        .addr   LAE95                           ; 80E6
        .addr   L_AF3A                          ; 80E8
        .addr   LAF61                           ; 80EA
        .addr   ObjHandler_Tank_76_Shooter_Init ; 80EC
        .addr   ObjHandler_Tank_77_Shooter_Main ; 80EE
        .addr   L_B076                          ; 80F0
        .addr   LB095                           ; 80F2
        .addr   L_B16E                          ; 80F4
        .addr   LB18F                           ; 80F6
        .addr   LB250                           ; 80F8
        .addr   LB2EC                           ; 80FA
        .addr   L_B337                          ; 80FC
        .addr   LB34F                           ; 80FE
        .addr   L_B3E3                          ; 8100
        .addr   LB3FE                           ; 8102
        .addr   L_B494                          ; 8104
        .addr   LB4A3                           ; 8106
        .addr   LB53A                           ; 8108
        .addr   L_B578                          ; 810A
        .addr   LB58B                           ; 810C
        .addr   LB680                           ; 810E
        .addr   L_B6E4                          ; 8110
        .addr   LB6F4                           ; 8112
        .addr   L_B832                          ; 8114
        .addr   LB843                           ; 8116
        .addr   L_B91A                          ; 8118
        .addr   LB94A                           ; 811A
        .addr   LB97A                           ; 811C
        .addr   LBA00                           ; 811E
        .addr   L_BA88                          ; 8120
        .addr   LBAA4                           ; 8122
.endmacro

